version: "3"
services:
    epayco:
        container_name: ${APP_NAME}
        build: .
        ports:
            - "8090:80"
        env_file:
            - .env
        volumes:
            - .:/var/www/html:cached
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        depends_on:
            - epayco-db

    epayco-db:
        image: mysql:5.7.12
        container_name: epayco-db
        ports:
            - "3316:3306"
        env_file:
            - .env
        volumes:
            - epayco-db:/var/lib/mysql

volumes:
    epayco-db:
